### ISSUE TITLE
Gallery Template

### ISSUE THREAD

**Issue by Saishreekouda** [RR-Sahoo/Fronteesign#46]
I can contribute the template of a gallery page that can be edited accordingly by the user. It has cool hover effects and it has responsive design as well. Please refer - https://saishreekouda.github.io/MyProject/second.html

**Comment by Saishreekouda** [comment]
Please assign this issue to me under Hacktoberfest 2022

**Comment by RR-Sahoo** [comment]
Ok

**Comment by RR-Sahoo** [comment]
If you like this give a star.
