### ISSUE TITLE
Hero page template

### ISSUE THREAD

**Issue by Saishreekouda** [RR-Sahoo/Fronteesign#49]
Hero page is the landing page, something like this-
https://terra-green.herokuapp.com/recycle.html
I will make it into a template so that others can edit it easily.
Please assign me this issue under hacktoberfest.

**Comment by RR-Sahoo** [comment]
Its same like the next one you show in the about us template issue.  So do it once. I already assign that one to you under hacktober fest. That's why I closed this issue.
