### ISSUE TITLE
Form Validator

### ISSUE THREAD

**Issue by incognion** [RR-Sahoo/Fronteesign#51]
#### If user try to go ahead with empty sign up form, it shows error. Or in case if have less than required characters in username or password, it'll warn user.
![image](https://user-images.githubusercontent.com/97580124/194205333-9db24b69-3d0f-46c4-a90e-939e15407f8a.png)

**Comment by RR-Sahoo** [comment]
ok

**Comment by RR-Sahoo** [comment]
if you like this hit a star.
